backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "ustawienia"
    label: "⚙️ Ustawienia strony"
    files:
      - name: "glowne"
        label: "Główne ustawienia"
        file: "settings.json"
        fields:
          - { label: "Tytuł strony", name: "title", widget: "string", default: "Szklowelove - Sprzedaż szkła z pasją" }
          - { label: "Opis na stronie głównej", name: "description", widget: "text" }
          - { label: "Link do Facebooka", name: "facebook", widget: "string" }
          - { label: "Link do Instagrama", name: "instagram", widget: "string" }
          - { label: "Link do Vinted", name: "vinted", widget: "string" }

  - name: "produkty"
    label: "🛍️ Produkty"
    folder: "produkty"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa produktu", name: "title", widget: "string" }
      - label: "Zdjęcia"
        name: "images"
        widget: "list"
        field: { label: "Zdjęcie", name: "image", widget: "image" }
